### ISSUE TITLE
Keycloak integration

### ISSUE THREAD

**Issue by JonasCir** [hzi-braunschweig/SORMAS-Docker#122]
Hi there :smiley: 
On `development` `docker-compose-keycloak.yml` currently contains an additional `postgres` and `pg_dump` container for keycloak. 
As the   `keycloak-postgres ` basically seems to need no [additional setup](https://github.com/hzi-braunschweig/SORMAS-Docker/tree/development/keycloak-postgres), would it be possible to reuse the existing `postgres` and `pg_dump` to reduce the size and complexity of the setup @vidi42?

Best,
Jonas

**Comment by vidi42** [comment]
Hey @JonasCir

**Comment by vidi42** [comment]
Hey @JonasCir 
Theoretically yes, the same `postgres` and `pg_dump` can be used for Keycloak and SORMAS, but that's not without a small setup.
Because Keycloak requires and existing DB and user to connect with, the `postgres` container needs to set those up, so `hzibraunschweig/sormas-postgres` will have to setup a different DB or schema for Keycloak to use, otherwise the Keycloak and SORAMS tables will be mixed up.

**Comment by JonasCir** [comment]
Alright thanks. Today, I actually learned about some cases where it might be beneficial to separate the databases :)
