### ISSUE TITLE
i was testing sormas docker before installing to test server and having issue after pulling the docker images i'm running ubuntu 18.04 

### ISSUE THREAD

**Issue by tronbiniyam** [hzi-braunschweig/SORMAS-Docker#47]
ERROR: for sormas-docker_postgres_1  Cannot start service postgres: error while creating mount source path '/srv/dockerdata/sormas/psqldata': mkdir /srv/dockerdata: read-only file system

ERROR: for pg_dump  Cannot start service pg_dump: error while creating mount source path '/backup': mkdir /backup: read-only file system

ERROR: for postgres  Cannot start service postgres: error while creating mount source path '/srv/dockerdata/sormas/psqldata': mkdir /srv/dockerdata: read-only file system
ERROR: Encountered errors while bringing up the project.

**Comment by TomHutter** [comment]
The sormas and the postgres container try to create folders on your host under /srv/dockerdata, the pg_dump container tries to create a folder /backup on your host. Creating this folders is not possible, since the file system on your host is read-only.

Try to create host folders for your container volumes in a read-write file system on your host. e.g.

~~~bash
~ # mount 

/dev/mapper/vg00-home on /home type xfs (rw,relatime,attr2,inode64,logbufs=8,logbsize=32k,noquota)
~~~

Important, is the rw flag right behind the opening bracket '(**rw**,'. 

Change `.env` then to some path on the rw file system e.g.:

~~~bash
SORMAS_PATH=/home/dockerdata/sormas    
~~~

Do the same with the `/backup/` folder for the pg_dump container in `docker-compose.yml`:

~~~yaml
   volumes:
      - /home/backup:/var/opt/db_dumps
~~~

**Comment by nliakm** [comment]
Closed due to inactivity.
